version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Hadolint
          command: docker run --rm --interactive hadolint/hadolint:latest < Dockerfile
  test-app:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run:
          name: run tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t ghcr.io/audif90/karsajobs:latest .
      - run:
          name: Authenticate to GitHub Packages
          command: echo "${CR_PAT}" | docker login ghcr.io -u "${USERNAME}" --password-stdin
      - run:
          name: push to GitHub Packages
          command: docker push ghcr.io/audif90/karsajobs:latest
    
workflows:
  lint_and_test:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs

# VS Code Extension Version: 1.2.0